config/routes.rb
Rails.application.routes.draw do

	root to: 'static#home'

	delete 'phases/:id/reset' => 'responses#reset_phase'

	resources :agencies

	resources :funding_sources

	resources :tasks

	resources :treatment_strategies do
		put :update_individual, on: :collection
	end

	resources :treatment_adaptations do
		put :update_individual, on: :collection
	end

	resources :agency_treatments do
		put :update_individual, on: :collection
	end

	resources :messages

	resources :pages do
		get :admin, on: :collection
	end

	resources :phases do
		resources :steps do
			resources :activities
		end
	end

	resources :responses
	
	resources :team do
		get :manage, on: :collection
	end

	resources :treatment_adaptations
	
	resources :users

	resources :user_events

	devise_scope :user do
		get '/login' => 'sessions#new', as: 'login'
		get '/logout' => 'sessions#destroy', as: 'logout'
		get '/register' => 'registrations#new', as: 'register'
	end


	devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions' }
	

	get '/admin' => 'admin#index', as: :admin_index
	get '/dashboard' => 'dashboard#index', as: :dashboard_index
	get '/progress/:agency_id' => 'progress#index', as: :agency_progress
	get '/progress/:agency_id/:phase' => 'progress#show', as: :agency_phase_progress

	# quick catch-all route for static pages
	get '/:id', controller: 'pages', action: :show
	# get '/:action', controller: 'static'	

end

app/views/admin/index.html.haml
.container
	.row
		.col-sm-12
			%h1
				Hi
				= current_user.name.titleize
	.row
		.col-sm-10
			= form_tag admin_index_path, method: :get, class: 'form-inline' do
				= select_tag :facilitator_id, options_from_collection_for_select( User.admin, :id, :name, params[:facilitator_id] ), prompt: 'All', class: 'form-control'
				= submit_tag 'Filter', class: 'btn btn-primary'
		.col-sm-2
			

	%a.btn.btn-primary.pull-right{ href: users_path, style: 'margin: 0 1em;' }
		Manage Facilitators


	%a.btn.btn-success.pull-right{ { data: { toggle: :modal, target: '#new_agency' } } }
		Add Agency

	- if @agencies.present?
		%table.table
			%thead
				%th
					Name
					%a{ href: admin_index_path( sort_by: 'name', sort_dir: 'asc' ) }
						%i.fa.fa-arrow-up
					%a{ href: admin_index_path( sort_by: 'name', sort_dir: 'desc' ) }
						%i.fa.fa-arrow-down
				%th
					Joined
					%a{ href: admin_index_path( sort_by: 'created_at', sort_dir: 'asc' ) }
						%i.fa.fa-arrow-up
					%a{ href: admin_index_path( sort_by: 'created_at', sort_dir: 'desc' ) }
						%i.fa.fa-arrow-down
				%th
					Facilitator
				%th
					Lead
				%th
					Team Members
				%th
				%th
				%th

			%tbody
				- @agencies.each do |agency|
					%tr
						%td
							= link_to agency.name, edit_agency_path( agency )
						%td
							= time_ago_in_words agency.created_at
							ago
						%td
							- if agency.facilitator != nil
								= agency.facilitator.name.titleize
						%td
							- if agency.users.present?
								- if agency.lead.present?
									= agency.lead.name.titleize
						%td
							= agency.users.count
							= link_to 'Manage Team', manage_team_index_path( agency_id: agency.id )
						%td
							%a{ href: edit_agency_path( agency ) }
								%i.fa.fa-pencil
								Edit
						%td
							%a{ href: agency_progress_path( agency ) }
								%i.fa.fa-eye
								Review Progress
						%td
							%a.btn.btn-danger{ href: agency_path( agency ), data: { method: :delete, confirm: 'Are you sure?' } }
								%i.fa.fa-trash-o
								Delete
	- else
		%h3 No Agencies



= render 'agencies/new_modal'