config/routes.rb
Rails.application.routes.draw do

	root to: 'static#home'

	delete 'phases/:id/reset' => 'responses#reset_phase'

	resources :agencies

	resources :funding_sources

	resources :tasks

	resources :treatment_strategies do
		put :update_individual, on: :collection
	end

	resources :treatment_adaptations do
		put :update_individual, on: :collection
	end

	resources :agency_treatments do
		put :update_individual, on: :collection
	end

	resources :messages

	resources :pages do
		get :admin, on: :collection
	end

	resources :phases do
		resources :steps do
			resources :activities
		end
	end

	resources :responses
	
	resources :team do
		get :manage, on: :collection
	end

	resources :treatment_adaptations
	
	resources :users

	resources :user_events

	devise_scope :user do
		get '/login' => 'sessions#new', as: 'login'
		get '/logout' => 'sessions#destroy', as: 'logout'
		get '/register' => 'registrations#new', as: 'register'
	end


	devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions' }
	

	get '/admin' => 'admin#index', as: :admin_index
	get '/dashboard' => 'dashboard#index', as: :dashboard_index
	get '/progress/:agency_id' => 'progress#index', as: :agency_progress
	get '/progress/:agency_id/:phase' => 'progress#show', as: :agency_phase_progress

	# quick catch-all route for static pages
	get '/:id', controller: 'pages', action: :show
	# get '/:action', controller: 'static'	

end

app/models/agency.rb
class Agency < ActiveRecord::Base

	enum status: { 'active' => 1, 'archive' => 2 }

	belongs_to	:facilitator, class_name: 'User'

	has_many 	:agency_users, dependent: :destroy
	has_many	:users, through: :agency_users

	has_many	:budget_items, dependent: :destroy
	
	has_many	:funding_sources, dependent: :destroy
	has_many	:treatment_strategies, dependent: :destroy
	has_many	:treatment_adaptations, dependent: :destroy
	has_many	:agency_treatments, dependent: :destroy

	has_many	:messages, dependent: :destroy
	has_many	:respondings, dependent: :destroy
	has_many	:responses, dependent: :destroy

	has_many	:tasks, dependent: :destroy

	has_many	:treatments

  	after_create :create_treatment_strategies
  	after_create :create_treatment_adaptations
  	after_create :create_agency_treatments


  	def to_csv(agency)
  		CSV.generate do |csv|
  			csv << [agency.name]
			csv << ['Phase', 'Step', 'Activity', 'Question Number', 'Question', 'Response', 'Recorded At']
			agency.responses.order("phase_id ASC", "question_id ASC").each do |response|
				if response.question.name.present?
					question = response.question.name 
				else 
					question = response.question.content
				end
				
				csv << [response.phase_id, response.step_id, response.activity_id, response.question_id, 
					question, response.content, response.created_at
				]
			end

			csv << ['Funding Source', 'Offer Funding?', 'Reimbursement Rate']
			agency.funding_sources.order("id ASC").each do |funding_source|
				csv << [funding_source.name, funding_source.offer_funding, funding_source.reimbursement_rate]
			end

			csv << ['Treatment Adaptation', 'Reasons for Adaptation', 'Specific Concerns', 'Addressing Concerns', 'Details', 'Implementer', 'No longer doing adaptation']
			agency.treatment_adaptations.order("id ASC").each do |ta|
				csv << [
					ta.name,[ta.org_level, ta.provider_factors, ta.client_chars,
					ta.system_level, ta.other_reasons], [ ta.concerns, ta.other_concerns],
					[ta.proceed_with_plan, ta.seek_further_consultation, ta.address_concern, ta.address_concern_text],
					ta.adaptation_details, [ta.treatment_developer, ta.researcher, ta.agency_leader, ta.supervisor, ta.direct_provider, ta.implementation_team, ta.other_implementer],
					ta.not_doing_adaptation
					]
			end	

			csv << ['Specific strategy', 'Considerations', 'Selected for use', 'Details', 'Implementer']
			agency.treatment_strategies.order("id ASC").each do |ts|
				csv << [ts.name, [ts.use_currently, ts.feasible, ts.previous_success, ts.recommended],
						ts.selected, ts.specifics, ts.implementer
						]
			end	
			csv << ['Chosen Treatment']
			csv << [agency.agency_treatments.first.chosen_treatment] if agency.agency_treatments.first.chosen_treatment.present?
			csv << ['Task', 'Concerns', 'Satisfaction Level', 'Due', 'Assigned', 'Details']
			agency.tasks.order("id ASC").each do |ts|
				csv << [ts.name, ts.concerns, ts.satisfaction_level, ts.due_at, ts.assigned_to, ts.content]
			end	
		end
  	end

  	def create_treatment_strategies
  		[
			"Develop agency leader characteristics supporting innovation and implementation", 
			"Recruit, designate, and train leaders for the change effort", 
			"Leaders mandate the use of the intervention strategies and packages", 
			"Conduct local consensus discussions", 
			"Involve existing governing structures in the implementation effort", 
			"Identify and prepare agency champions",
			"Involve clients and family members in the implementation effort",
			"Inform agency opinion leaders",
			"Recruit and cultivate relationships with partners in the implementation effort",
			"Develop resource sharing agreements",
			"Obtain formal commitments from key partners",
			"Develop academic partnerships",
			"Alter incentive/allowance structures",
			"Pay direct providers a set amount per client/family for delivering the new intervention",
			"Penalize direct providers financially for failure to implement the intervention",
			"Create fee structure where clients pay less for preferred interventions and more for less preferred interventions",
			"Work to place intervention on lists of actions for which providers can be reimbursed",
			"Fund and contract for the intervention",
			"Access new or existing money to facilitate the implementation and sustainment",
			"Make billing easier for the intervention",
			"Shift and revise roles among professionals who provide care; redesign job characteristics",
			"Change who serves on the clinical staff, adding different disciplines/skills to make it more likely the intervention will be delivered and/or be more successful",
			"Change the physical structure and/or intervention materials to facilitate implementation",
			"Change the location of clinical service sites to increase access to new intervention",
			"Change records systems to allow better assessment",
			"Facilitate relay of clinical data to direct providers",
			"Develop reminder systems designed to prompt direct providers to use the new intervention",
			"Pilot test the implementation effort and then gradually move to system-wide roll-out",
			"Model of simulate changes that will be implemented prior to system-wide implementation",
			"Implement changes in a cyclical fashion using small tests of change before taking changes system-wide",
			"Monitor clinical progress or outcomes for the purpose of quality assurance and improvement (Note: This should be paired with another implementation or sustainment strategy)",
			"Involve multiple kinds of stakeholders in a group to oversee use of the intervention",
			"Create a learning collaborative (also known as peer consultation networks, communities of practice, etc.) to support delivery of the intervention",
			"Provide direct providers ongoing supervision on the use of the new intervention",
			"Provide ongoing training for supervisors who will supervise direct providers using the new intervention",
			"Obtain commitment from direct providers to use self-monitoring fidelity techniques",
			"Develop and utilize fidelity-monitoring strategies, such as supervision, audit and feedback",
			"Develop and use a system to deliver technical assistance on the implementation of intervention",
			"Develop a system to monitor adherence to the implementation effort",
			"Allow direct providers protected time to reflect and support each other’s implementation effort",
			"Create/increase opportunities for clients and families to provide feedback about implementation of the intervention",
			"Leader prioritization and support",
			"Agency priorities and/or program needs are aligned with the new intervention ",
			"Maintain workforce skills through continued training, booster training sessions, supervision and feedback",
			"Maintain staff buy-in ",
			"Fund and contract for the intervention’s continued use",
			"Access new or existing money to facilitate sustainment",
			"Systematic adaptation of the intervention to increase fit/ compatibility of intervention with the agency",
			"Mutual adaptation between the intervention and agency (e.g., adaptation of the intervention to improve fit, alignment of the agency procedures with the intervention)"
		].each do |t|
			treatment_strategy = self.treatment_strategies.build name: t
			treatment_strategy.save
		end
  	end

  	def create_treatment_adaptations
  		[
  			"Tailoring/tweaking/refining the intervention",
			"Integrating components of the intervention into another framework",
			"Integrating another treatment into the intervention",
			"Removing/skipping core modules or components of the intervention",
			"Lengthening/extending session time",
			"Shortening/condensing session time",
			"Lengthening/extending number of weeks",
			"Shortening/condensing number of weeks",
			"Adjusting the order of intervention modules, topics, or segments",
			"Adding modules or topics to the intervention",
			"Not using/departing from the intervention",
			"Loosening the session structure",
			"Repeating elements or modules",
			"Substituting elements or modules",
			"Changing the setting",
			"Changing who delivers the intervention",
			"Changing the format by which the treatment is delivered",
			"Changing the target population for the intervention"
		].each do |t|
			treatment_adaptation = self.treatment_adaptations.build name: t
			treatment_adaptation.save
		end
  	end

  	def create_agency_treatments
		agency_treatment = self.agency_treatments.build
		agency_treatment.save
  	end

	def activity_complete?( activity )
		if activity.id == 10
			self.funding_sources.present? || self.responses.where( activity_id: activity.id ).count >= activity.questions.count
		elsif activity.id == 12
			self.agency_treatments.first.chosen_treatment.present?
		else
			self.responses.where( activity_id: activity.id ).count >= activity.questions.where( required: true ).count
		end
	end

	def training_requirements_complete?( activity )
		self.responses.where( activity_id: activity.id ).count >= activity.questions.where( required: true ).count || 
		if self.responses.where( activity_id: activity.id ).first.present?
			self.responses.where( activity_id: activity.id ).first.content != 'yes' 
		end
	end

	def treatment_strategies_complete?
		self.treatment_strategies.where( :selected => true ).count >= 1	
	end

	def phase_complete?( phase )
		if phase.id == 1
			return self.responses.where( question_id: 1 ).last.try( :content ) == 'yes' && self.responses.where( question_id: 2 ).last.try( :content ) == 'yes'
		end
		self.responses.where( phase_id: phase.id ).count >= phase.questions.where( required: true ).count
	end

	def step_complete?( step )
		self.responses.where( step_id: step.id ).count >= step.questions.where( required: true ).count
	end

	def lead
		self.agency_users.find_by(role: "lead").try( :user )
	end

	def to_s
		self.name
	end
	
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController


	def create
		@agency = Agency.new( agency_params )

		if @agency.save
			redirect_to edit_agency_path( @agency )
		else
			render :new
		end

	end

	def destroy
		@agency = Agency.find( params[:id] )
		@agency.destroy
		redirect_to admin_index_path
	end

	def edit
		@agency = Agency.find( params[:id] )	
	end

	def show
		@agency = Agency.find( params[:id] )
	end

	def update
		@agency = Agency.find( params[:id] )
		if @agency.update( agency_params )
			
			if @agency.users.exists? && params[:lead_id].present?
				AgencyUser.where( agency_id: @agency.id, role: 'lead').last.update( role: 'member' )
				AgencyUser.where( agency_id: @agency.id, user_id: params[:lead_id] ).last.update( role: 'lead' )
			end

			if params[:assessment_complete].present?
				res = @agency.responses.where( question_id: 1 ).first_or_initialize
				res.update( content: 'yes' )
			else
				res = @agency.responses.where( question_id: 1 ).first
				res.update( content: 'no' ) if res.present?
			end

			if params[:receptive_to_treatment].present?
				res = @agency.responses.where( question_id: 2 ).first_or_initialize
				res.update( content: 'yes' )
			else
				res = @agency.responses.where( question_id: 2 ).first
				res.update( content: 'no' ) if res.present?
			end

			redirect_to admin_index_path
		else
			render :edit
		end
	end

	private


		def agency_params
			params.require( :agency ).permit( :facilitator_id, :name, :description, :notes, :address1, :address2, :city, :state, :zip, :phone, :status, :lead_id )
		end


end

app/views/agencies/_new_modal.html.haml
#new_agency.modal.fade
	.modal-dialog
		.modal-content
			.modal-header
				%button.close{ type: :button, 'data-dismiss' => 'modal', 'aria-hidden' => 'true' }
					&times;
				%h4.modal-title
					New Agency
			= form_for Agency.new( facilitator_id: current_user.id ) do |f|
				.modal-body
					.form-group
						= f.label :name
						= f.text_field :name, class: 'form-control'
					.form-group
						= f.label :facilitator_id
						= f.collection_select :facilitator_id, User.admin, :id, :name, {}, class: 'form-control'

				.modal-footer
					%button.btn.btn-default{ type: :button, 'data-dismiss' => 'modal' }
						Close
					= f.submit 'Create', class: 'btn btn-primary'

app/views/agencies/edit.html.haml
.container
	.row
		.col-sm-12
			%ol.breadcrumb
				%li
					= link_to 'Admin', admin_index_path
				%li
					= link_to @agency.name, agency_path( @agency )
				%li
					Edit
.container
	.row
		.col-sm-10
			%h1
				Edit
				= @agency.name
		.col-sm-2
			.pull-right
				%a.btn.btn-danger{ href: agency_path( @agency ), data: { method: :delete, confirm: 'Are you sure?' } }
					%i.fa.fa-trash-o
					delete
	.row
		= form_for @agency do |f|
			.col-sm-8
				.form-group
					= f.label :name
					= f.text_field :name, class: 'form-control'
				.form-group
					= f.label :description
					= f.text_area :description, class: 'form-control'
				.form-group
					= f.label :address1
					= f.text_field :address1, class: 'form-control'
				.form-group
					= f.label :address2
					= f.text_field :address2, class: 'form-control'
				.row.form-group
					.col-sm-6
						= f.label :city
						= f.text_field :city, class: 'form-control'
					.col-sm-4
						= f.label :state
						= f.text_field :state, class: 'form-control'
					.col-sm-2
						= f.label :zip
						= f.text_field :zip, class: 'form-control'
				.form-group
					= f.label :phone
					= f.text_field :phone, class: 'form-control'
			.col-sm-4
				.well
					.form-group
						= f.label :facilitator_id
						= f.collection_select :facilitator_id, User.admin, :id, :name, {}, class: 'form-control'
					%hr
					.form-group
						%label{ for: :agency_lead_id }
							.pull-right{ style: 'margin-left:4em;' }
								%a.btn.btn-sm.btn-success{ data: { toggle: :modal, target: '#new_user' } }
									Add
							Lead
					- if @agency.users.exists?
						= select_tag :lead_id, options_from_collection_for_select( @agency.users, :id, :name, @agency.lead.id ), class: 'form-control'
						%br
						%label
							= link_to 'Manage Team', manage_team_index_path( agency_id: @agency.id )

					%hr
						%table.table
							%tr
								%td
									Viewed Phase 1 Dashboard?
								%td
									%b
										- if UserEvent.where( agency_id: @agency.id ).find_by( content: 'viewed Phase 1 Dashboard' ).present?
											Yes
										- else
											No

							%tr
								%td
									Viewed Phase 1 Step 1?
								%td
									%b
										- if UserEvent.where( agency_id: @agency.id ).find_by( content: 'viewed Phase 1 Step 1 Instructions' ).present?
											Yes
										- else
											No
							%tr
								%td
									Viewed Phase 1 Step 2?
								%td
									%b
										- if UserEvent.where( agency_id: @agency.id ).find_by( content: 'viewed Phase 1 Step 2 Instructions' ).present?
											Yes
										- else
											No
							%tr
								%td
									= link_to 'View All Agency Events', user_events_path( agency_id: @agency.id )
								%td

						.form-group
							= check_box_tag :assessment_complete, 'yes', @agency.responses.where( question_id: 1 ).last.try( :content ) == 'yes'
							Assessment complete?
						.form-group
							= check_box_tag :receptive_to_treatment, 'yes', @agency.responses.where( question_id: 2 ).last.try( :content ) == 'yes'
							Receptive to treatment?
					%hr
						.form-group
							= f.label :status
							= f.collection_select :status, Agency.statuses, :first, :first, {}, class: 'form-control'
					%hr
					.form-group
						= f.submit class: 'btn btn-primary'
%br
%br
%br
%br
		

= render 'users/new_modal', args: { agency_id: @agency.id, lead: true }

app/views/agencies/new.html.haml
.container
	.row
		.col-sm-12
			%ol.breadcrumb
				%li
					= link_to 'Admin', admin_index_path
				%li
					New Agency
.container
	.row
		.col-sm-12
			%h1
				Add an Agency
		.col-sm-8
			= render 'form', agency: Agency.new

app/views/agencies/show.html.haml
.container
	.row
		.col-sm-12
			%ol.breadcrumb
				%li
					= link_to 'Admin', admin_index_path
				%li
					= @agency.name

	.row
		.col-sm-12
			%h1
				= @agency.name
			%a.btn.btn-success.pull-right{ { data: { toggle: :modal, target: '#new_message' } } }
				Message






= render 'messages/new_modal', args: { agency_id: @agency.id }