config/routes.rb
Rails.application.routes.draw do

	root to: 'static#home'

	delete 'phases/:id/reset' => 'responses#reset_phase'

	resources :agencies

	resources :funding_sources

	resources :tasks

	resources :treatment_strategies do
		put :update_individual, on: :collection
	end

	resources :treatment_adaptations do
		put :update_individual, on: :collection
	end

	resources :agency_treatments do
		put :update_individual, on: :collection
	end

	resources :messages

	resources :pages do
		get :admin, on: :collection
	end

	resources :phases do
		resources :steps do
			resources :activities
		end
	end

	resources :responses
	
	resources :team do
		get :manage, on: :collection
	end

	resources :treatment_adaptations
	
	resources :users

	resources :user_events

	devise_scope :user do
		get '/login' => 'sessions#new', as: 'login'
		get '/logout' => 'sessions#destroy', as: 'logout'
		get '/register' => 'registrations#new', as: 'register'
	end


	devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions' }
	

	get '/admin' => 'admin#index', as: :admin_index
	get '/dashboard' => 'dashboard#index', as: :dashboard_index
	get '/progress/:agency_id' => 'progress#index', as: :agency_progress
	get '/progress/:agency_id/:phase' => 'progress#show', as: :agency_phase_progress

	# quick catch-all route for static pages
	get '/:id', controller: 'pages', action: :show
	# get '/:action', controller: 'static'	

end

app/models/user_event.rb
class UserEvent < ActiveRecord::Base

	enum status: { 'active' => 1, 'archive' => 2, 'trash' => 3 }

	belongs_to 		:user
	belongs_to		:agency
	belongs_to		:parent_obj, polymorphic: true

	### Class Methods   	--------------------------------------

	def self.by_object( obj )
		return scoped if obj.nil?
		where( parent_obj_type: obj.class.name, parent_obj_id: obj.id )
	end

	def self.dated_between( start_date=1.month.ago, end_date=1.month.from_now )
		where( "created_at between ? and ?", start_date, end_date )
	end

	def self.recent( num=10 )
		order( 'created_at desc' ).limit( num )
	end

	
	def self.record( name, args={} )
		return false unless name = name.to_s
		user_id = args[:user].try( :id )
		agency_id = args[:agency].try( :id ) || args[:user].try( :agency )
		parent_obj = args[:on] || args[:obj] || args[:parent_obj]


		rate = args[:rate] || 5.minutes

		# setting owner_type so logging with nill owner doesn't populate owner_type with NilClass
		parent_obj_type = parent_obj.nil? ? nil : parent_obj.class.name

		dup_events = self.where( name: name, user_id: user_id ).within_last( rate )
		dup_events = dup_events.by_object( parent_obj ) if parent_obj.present?
		# DO NOT record if existing events within rate
		return false if dup_events.count > 0
		
		event = self.create( 	name: name, 
								user_id: user_id, 
								agency_id: agency_id,
								parent_obj: parent_obj,
								value: args[:value],
								content: args[:content]
							)

		return event

	end


	def self.within_last( period=1.minute )
		period_ago = Time.zone.now - period
		where( "created_at >= ?", period_ago )
	end


end

app/controllers/user_events_controller.rb
class UserEventsController < ApplicationController


	def index
		sort_by = params[:sort_by] || 'created_at'
		sort_dir = params[:sort_dir] || 'desc'

		@events = UserEvent.order( "#{sort_by} #{sort_dir}" )

		if params[:name].present?
			@events = @events.where( name: params[:name].downcase )
		end

		if params[:agency_id].present?
			@events = @events.where( agency_id: params[:agency_id].downcase )
		end

		@events = @events.page( params[:page] )

	end

	def destroy
		@event = UserEvent.find_by(id: params[:id])
		@event.destroy
		redirect_to user_events_path
	end
end

app/views/user_events/index.html.haml
.container
	.row
		.col-xs-10
			%ul.breadcrumb
				%li
					= link_to 'Admin', admin_index_path
				%li
					%strong
						Events
	.row
		.col-xs-4
			= raw paginate @events
		.col-xs-8
			= form_tag user_events_path, method: :get, class: 'form-inline' do
				Agency:
				= select_tag :agency_id, options_from_collection_for_select( Agency.all, :id, :name, params[:agency_id] ), prompt: 'All', class: 'form-control'
				&nbsp;&nbsp;
				Event:
				= select_tag :name, options_from_collection_for_select( UserEvent.select( :name ).distinct, :name, :name, params[:name] ), prompt: 'All', class: 'form-control'
				= submit_tag 'Filter', class: 'btn btn-primary'
				= link_to 'Clear', user_events_path, class: 'btn btn-default btn-xs'
	.row
		.col-xs-12
			%table.table
				%thead
					%th Name
					%th Agency
					%th User
					%th Content
					%th Parent Obj
					%th Happened
					%th
				%tbody
					- @events.each do |event|
						%tr
							%td
								= link_to event.name, edit_user_event_path( event.id )
							%td
								= event.agency || 'N/A'
							%td
								= event.user
							%td
								= raw event.content
							%td
								= event.parent_obj || 'None'
							%td
								= time_ago_in_words event.created_at
								ago
							%td
								.btn-group
									%button.btn.btn-mini.btn-default
										%a{ href: user_event_path( event ), data: { method: 'delete', confirm: 'Are you sure?' } }
											%i.fa.fa-trash-o
											Delete