config/routes.rb
Rails.application.routes.draw do

	root to: 'static#home'

	delete 'phases/:id/reset' => 'responses#reset_phase'

	resources :agencies

	resources :funding_sources

	resources :tasks

	resources :treatment_strategies do
		put :update_individual, on: :collection
	end

	resources :treatment_adaptations do
		put :update_individual, on: :collection
	end

	resources :agency_treatments do
		put :update_individual, on: :collection
	end

	resources :messages

	resources :pages do
		get :admin, on: :collection
	end

	resources :phases do
		resources :steps do
			resources :activities
		end
	end

	resources :responses
	
	resources :team do
		get :manage, on: :collection
	end

	resources :treatment_adaptations
	
	resources :users

	resources :user_events

	devise_scope :user do
		get '/login' => 'sessions#new', as: 'login'
		get '/logout' => 'sessions#destroy', as: 'logout'
		get '/register' => 'registrations#new', as: 'register'
	end


	devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions' }
	

	get '/admin' => 'admin#index', as: :admin_index
	get '/dashboard' => 'dashboard#index', as: :dashboard_index
	get '/progress/:agency_id' => 'progress#index', as: :agency_progress
	get '/progress/:agency_id/:phase' => 'progress#show', as: :agency_phase_progress

	# quick catch-all route for static pages
	get '/:id', controller: 'pages', action: :show
	# get '/:action', controller: 'static'	

end

app/models/activity.rb
class Activity < ActiveRecord::Base

	before_save :set_parents

	belongs_to 	:phase
	belongs_to  :step

	has_many	:questions
	has_many	:respondings
	has_many 	:responses



	def to_s
		self.name
	end

	def to_csv(current_agency)
		CSV.generate do |csv|

			if self.id == 9
				csv << ['Funding Sources']
				current_agency.funding_sources.order("id ASC").each do |funding|
					csv << [funding.name]
					csv << [funding.offer_funding]
					csv << [funding.reimbursement_rate]
				end
			end

			if self.id == 11 
				csv << ['Treatment Strategies']
				current_agency.treatment_strategies.order("id ASC").each do |treatment_strategies|
					csv << [treatment_strategies.attributes]
				end	

			elsif self.id == 12
				csv << ['Prospective Adaptations', 'No Longer Considering Adaptation']
				current_agency.treatment_adaptations.order("id ASC").each do |treatment_adaptations|
					csv << [treatment_adaptations.name, treatment_adaptations.not_doing_adaptation]
				end	

			elsif self.id == 13 
				csv << ['Treatment Adaptations']
				current_agency.treatment_adaptations.order("id ASC").each do |treatment_adaptations|
					csv << [treatment_adaptations.attributes]
				end

			else
				csv << ['Responses']
				self.responses.where(agency_id: current_agency.id).order("id ASC").each do |response|
					csv << [response.content]
				end
			end
		end
	end

	private
		def set_parents
			self.phase_id ||= self.step.phase.id
		end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

	def show
		@phase = Phase.find( params[:phase_id] )
		@step = Step.find( params[:step_id] )
		@activity = Activity.find( params[:id] )

		@agency_treatment = AgencyTreatment.find_by(agency_id: @current_agency.id)

		@responding = @current_agency.respondings.where( activity_id: @activity.id ).first_or_create
		@responding.touch
			
		UserEvent.record( :view, { user: current_user, agency: @current_agency, rate: 23.hours, parent_obj: @activity, content: "viewed #{@phase.label} Step #{@step.seq} Activity #{@activity.seq} " } )
		
		respond_to do |format|
			format.html { render "activities/phase_#{@phase.seq}_step_#{@step.seq}_activity_#{@activity.seq}" }
			if @activity.id == 4
				format.csv { send_data @agency_treatment.to_csv}				
			else
				format.csv { send_data @activity.to_csv(@current_agency) }
			end
		end
	end

end

app/views/activities/orig_phase_2_step_2_activity_4.html.haml
.container
	.row
		.col-sm-12
			%ol.breadcrumb
				%li
					= link_to 'Dashboard', dashboard_index_path
				%li
					= link_to 'Phase 2', phase_path( 2 )
				%li
					= link_to 'Step 2', phase_step_path( @phase, @step )
				%li
					Activity 4: Training Requirements
	.row
		.col-sm-12
			%h1
				Activity 4: Training Requirements

			%p
				This activity is designed to assist with evaluating the training requirements specified by the treatment developers or outside training organization that must be met in order to deliver the research-based treatment you are considering adopting. 
			%p
				To identify the training requirements of a new research-based treatment, search for the original treatment or treatment article on the Internet or in the research literature. 

			= form_tag responses_path do
				= hidden_field_tag :activity_id, @activity.id
				%h4
					Necessity for Training:
				1)	Are there training requirements that must be met in order to deliver the treatment? 
				%p
					= radio_button_tag "question_answers[#{@activity.questions.find_by( seq: 1 ).id}]", :yes, @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 1 ).id ).first.try( :content ) == 'yes'
					Yes
					%span{ style: 'margin: auto 0.5em;' }
					= radio_button_tag "question_answers[#{@activity.questions.find_by( seq: 1 ).id}]", :no, @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 1 ).id ).first.try( :content ) == 'no'
					No
					%span{ style: 'margin: auto 0.5em;' }
					= radio_button_tag "question_answers[#{@activity.questions.find_by( seq: 1 ).id}]", :dk, @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 1 ).id ).first.try( :content ) == 'dk'
					Don't Know

				%h4
					Staff Involved:
				1)	What staff are required to receive training? (Select all that apply)
				%table.table
					%tr
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 2 ).id}][]", 'Direct Providers', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 2 ).id ).pluck( :content ).include?( 'Direct Providers' )
							Direct Providers
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 2 ).id}][]", 'Support Staff', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 2 ).id ).pluck( :content ).include?( 'Support Staff' )
							Support Staff
					%tr
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 2 ).id}][]", 'Supervisors', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 2 ).id ).pluck( :content ).include?( 'Supervisors' )
							Supervisors
						%td
							Other
							= text_field_tag "question_answers[#{@activity.questions.find_by( seq: 3 ).id}]", @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 3 ).id ).first.try( :content )
					%tr
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 2 ).id}][]", 'Agency Leaders', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 2 ).id ).pluck( :content ).include?( 'Agency Leaders' )
							Agency Leaders
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 2 ).id}][]", 'dk', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 2 ).id ).pluck( :content ).include?( 'dk' )
							No requirements specified

				2)	Who is required to deliver training? (Select all that apply)
				%table.table
					%tr
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 4 ).id}][]", 'Direct Providers', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 4 ).id ).pluck( :content ).include?( 'Direct Providers' )
							Direct Providers
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 4 ).id}][]", 'Outside Trainer', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 4 ).id ).pluck( :content ).include?( 'Outside Trainer' )
							Outside Trainer
					%tr
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 4 ).id}][]", 'Supervisors', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 4 ).id ).pluck( :content ).include?( 'Supervisors' )
							Supervisors
						%td
							Other
							= text_field_tag "question_answers[#{@activity.questions.find_by( seq: 5 ).id}]", @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 5 ).id ).first.try( :content )
					%tr
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 4 ).id}][]", 'Agency Leaders', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 4 ).id ).pluck( :content ).include?( 'Agency Leaders' )
							Agency Leaders
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 4 ).id}][]", 'dk', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 4 ).id ).pluck( :content ).include?( 'dk' )
							No requirements specified
					%tr
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 4 ).id}][]", 'Support Staff', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 4 ).id ).pluck( :content ).include?( 'Support Staff' )
							Support Staff
						%td

				%h4
					Training Model:
				1)	Is there a specific training model required? (Select all that apply)
				%table.table
					%tr
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 6 ).id}][]", 'Didactics', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 6 ).id ).pluck( :content ).include?( 'Didactics' )
							Didactics
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 6 ).id}][]", 'Educational brochure/handout', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 6 ).id ).pluck( :content ).include?( 'Educational brochure/handout' )
							Educational brochure/handout
					%tr
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 6 ).id}][]", 'Workshop / Seminars', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 6 ).id ).pluck( :content ).include?( 'Workshop / Seminars' )
							Workshop / Seminars
						%td
							Other
							= text_field_tag "question_answers[#{@activity.questions.find_by( seq: 7 ).id}]", @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 7 ).id ).first.try( :content )
					%tr
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 6 ).id}][]", 'Online Training', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 6 ).id ).pluck( :content ).include?( 'Online Training' )
							Online Training
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 6 ).id}][]", 'dk', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 6 ).id ).pluck( :content ).include?( 'dk' )
							No requirements specified
					%tr
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 6 ).id}][]", 'On-the-job training', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 6 ).id ).pluck( :content ).include?( 'On-the-job training' )
							On-the-job training
						%td

				2)	Are there training strategies that are required to be used during trainings? (Select all that apply)
				%table.table
					%tr
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 8 ).id}][]", 'Didactics', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 8 ).id ).pluck( :content ).include?( 'Didactics' )
							Didactics
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 8 ).id}][]", 'Educational brochure/handout', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 8 ).id ).pluck( :content ).include?( 'Educational brochure/handout' )
							Educational brochure/handout
					%tr
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 8 ).id}][]", 'Workshop / Seminars', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 8 ).id ).pluck( :content ).include?( 'Workshop / Seminars' )
							Workshop / Seminars
						%td
							Other
							= text_field_tag "question_answers[#{@activity.questions.find_by( seq: 9 ).id}]", @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 9 ).id ).first.try( :content )
					%tr
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 8 ).id}][]", 'Online Training', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 8 ).id ).pluck( :content ).include?( 'Online Training' )
							Online Training
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 8 ).id}][]", 'dk', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 8 ).id ).pluck( :content ).include?( 'dk' )
							No requirements specified
					%tr
						%td
							= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 8 ).id}][]", 'On-the-job training', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 8 ).id ).pluck( :content ).include?( 'On-the-job training' )
							On-the-job training
						%td










				= submit_tag 'Submit'
				

app/views/activities/phase_2_step_2_activity_1.html.haml
.container
	.row
		.col-sm-12
			%ol.breadcrumb
				%li
					= link_to 'Dashboard', dashboard_index_path
				%li
					= link_to 'Phase 2', phase_path( 2 )
				%li
					= link_to 'Step 2', phase_step_path( @phase, @step )
				%li
					Activity 1: Treatment Fit
	.row
		.col-sm-12
			%h1
				Activity 1: Treatment Fit
			-#%p.larger
				<u>Goal</u>: Assess whether the potential research-based treatment will be compatible with your agency’s values and mission.

			%p
				Now that you've selected a potential treatment to adopt within your agency, it is important to evaluate the fit of the treatment with your agency’s values. The checklist below is designed to quickly think about the fit of the treatment that your agency is considering for implementation. Use the resources that helped you identify this research-based treatment to gather information about the treatment you are considering.

			%h3
				Evaluating Fit of the Treatment

			= form_tag responses_path do
				= hidden_field_tag :activity_id, @activity.id
				%table.table
					%thead
						%th
						%th
						%th
							Yes
						%th
							No
						%th.text-center
							Don't Know
					%tbody
						- @activity.questions.order( :seq ).each do |question|
							%tr
								%td
									= question.seq
								%td.col-md-10
									= question.content
								%td.text-center
									= radio_button_tag "question_answers[#{question.id}]", :yes, @current_agency.responses.where( question_id: question.id ).first.try( :content ) == 'yes'
								%td.text-center
									= radio_button_tag "question_answers[#{question.id}]", :no, @current_agency.responses.where( question_id: question.id ).first.try( :content ) == 'no'
								%td.text-center
									= radio_button_tag "question_answers[#{question.id}]", :dk, @current_agency.responses.where( question_id: question.id ).first.try( :content ) == 'dk'

				= submit_tag 'Save', class: 'btn btn-primary pull-right'

app/views/activities/phase_2_step_2_activity_3.html.haml
.container
	.row
		.col-sm-12
			%ol.breadcrumb
				%li
					= link_to 'Dashboard', dashboard_index_path
				%li
					= link_to 'Phase 2', phase_path( 2 )
				%li
					= link_to 'Step 2', phase_step_path( @phase, @step )
				%li
					Activity 3: Clinical Value and Research Validity
	.row
		.col-sm-12
			%h1
				Activity 3: Clinical Value and Research Validity
			-#%p.larger
				<u>Goal</u>: Evaluate the clinical value and research validity of the treatment you are considering to adopt within your agency.

			%p
				There are a many treatments available for individuals with ASD. Treatments may vary in terms of their clinical value and/or research validity. To make the most informed choices about a new treatment, it is important to assess these factors before making a decision about adopting the treatment. The scores obtained from the clinical value and validity can be summed up to provide guidance for adopting a research-based treatment at your agency.

			%p
				<b>Clinical Value</b>: How meaningful and important the benefits and outcomes achieved by the treatment are to your agency, service providers, and clients served.

			%p
				<b>Research Validity</b>: The evidence supporting the use of the research-based treatment. 

			%h3
				Evaluating the Clinical Value of the Treatment

			= form_tag responses_path do
				= hidden_field_tag :activity_id, @activity.id
				%table.table
					%thead
						%th
						%th
						%th.text-center
							Yes
						%th.text-center
							No
						%th.text-center
							Don't Know
					%tbody
						- @activity.questions.where( section: 'section_1' ).order( :seq ).each do |question|
							%tr
								%td
									= question.seq
								%td.col-md-10
									= raw question.content
								%td.text-center
									= radio_button_tag "question_answers[#{question.id}]", :yes, @current_agency.responses.where( question_id: question.id ).first.try( :content ) == 'yes'
								%td.text-center
									= radio_button_tag "question_answers[#{question.id}]", :no, @current_agency.responses.where( question_id: question.id ).first.try( :content ) == 'no'
								%td.text-center
									= radio_button_tag "question_answers[#{question.id}]", :dk, @current_agency.responses.where( question_id: question.id ).first.try( :content ) == 'dk'

				%h3
					Evaluating the Research Validity of the Treatment

				%table.table
					%thead
						%th
						%th
						%th.text-center
							Yes
						%th.text-center
							No
						%th.text-center
							Don't Know
					%tbody
						- @activity.questions.where( section: 'section_2' ).order( :seq ).each do |question|
							%tr
								%td
									= question.seq
								%td.col-md-10
									= raw question.content
								%td.text-center
									= radio_button_tag "question_answers[#{question.id}]", :yes, @current_agency.responses.where( question_id: question.id ).first.try( :content ) == 'yes'
								%td.text-center
									= radio_button_tag "question_answers[#{question.id}]", :no, @current_agency.responses.where( question_id: question.id ).first.try( :content ) == 'no'
								%td.text-center
									= radio_button_tag "question_answers[#{question.id}]", :dk, @current_agency.responses.where( question_id: question.id ).first.try( :content ) == 'dk'

				= submit_tag 'Save', class: 'btn btn-primary pull-right'

app/views/activities/phase_3_step_1_activity_1.html.haml
.container
	.row
		.col-sm-12
			%ol.breadcrumb
				%li
					= link_to 'Dashboard', dashboard_index_path
				%li
					= link_to 'Phase 3', phase_path( 3 )
				%li
					= link_to 'Step 1', phase_step_path( @phase, @step )
				%li
					Activity 1
	.row
		.col-sm-12
			%h1
				Activity 1: Gathering Treatment Materials
			%h4
				Introduction
			%p
				It is important to gather the treatment materials that describe the research-based treatment in great detail. This will assist you while your implementation team considers what potential adaptations may be needed. Treatment resources may include treatment manuals, materials, and information about treatment implementation. The 
				%a{ href: phase_step_path( Phase.second, Phase.second.steps.first ) }
					The resource, Identifying and Selecting ASD Treatments, 
				provides guidance on how to access many of these resources. 

			-#.well.highlight
				Gather treatment resources to assist in considering what potential adaptations may be needed. 

			%p
				Which of the following treatment materials were you able to obtain (check all that apply)?
			= form_tag responses_path do
				= hidden_field_tag :activity_id, @activity.id
				.separator{ style: 'margin-left:2em;' }
					= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 1 ).id}][]", 'none', @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 1 ).id ).pluck( :content ).include?( 'none' )
					&nbsp;&nbsp;
					None
				- @activity.questions.find_by( seq: 1 ).prompts.each do |prompt|
					.separator{ style: 'margin-left:2em;' }
						= check_box_tag "question_answers[#{@activity.questions.find_by( seq: 1 ).id}][]", prompt.content, @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 1 ).id ).pluck( :content ).include?( prompt.content )
						&nbsp;&nbsp;
						= prompt.content
				.separator{ style: 'margin-left:2em;' }
					Other:
					&nbsp;
					= text_field_tag "question_answers[#{@activity.questions.find_by( seq: 2 ).id}]", @current_agency.responses.where( question_id: @activity.questions.find_by( seq: 2 ).id ).first.try( :content )
				

				= submit_tag 'Save', class: 'btn btn-primary'

app/views/activities/phase_3_step_1_activity_2.html.haml
.container
	.row
		.col-sm-12
			%ol.breadcrumb
				%li
					= link_to 'Dashboard', dashboard_index_path
				%li
					= link_to 'Phase 3', phase_path( 3 )
				%li
					= link_to 'Step 1', phase_step_path( @phase, @step )
				%li
					Activity 2
	.row
		.col-sm-12
			%h1
				Activity 2: Evaluating Prospective Adaptations to the Treatment

			%p
				When adapting a research-based treatment you are considering adopting and implementing at your agency, it is important to consider and anticipate the types of adaptations you will be making to the treatment. The checklist below is a series of questions about potential adaptations to the treatment you are considering in order to make well-informed decisions for your Treatment Adaptation Plan.

			%p
				In the broadest sense, adaptations can include modifications to the: 

			%ul
				%li
					Content: How components of the treatment are delivered.
				%li
					Context: How the overall treatment is delivered.
			%p{ style: 'font-weight:bold;' }
				Gather treatment resources to assist in considering what potential adaptations may be needed. 

			%p
				Treatment resources may include treatment manuals, materials, and information about treatment implementation. The 
				%a{ href: '/phases/2/steps/3/activities/4' }
					Instructions for Identifying and Selecting ASD Treatments 
				provides guidance on how to access many of these resources. 

			%p{ style: 'font-weight:bold;' }
				Do you anticipate making the following content adaptations to the intervention you are considering at your agency: 

			%table.table
				%thead
					%th
					%th
					%th
						Yes
					%th
						No
					%th.text-center
						Don't Know
				%tbody
				-i = 0
				= form_tag update_individual_treatment_adaptations_path, :method => "put", :id => "myAdaptationsList" do |f|	
					- for treatment_adaptations in @current_agency.treatment_adaptations.order('created_at ASC')
						=fields_for "treatment_adaptations[]", treatment_adaptations do |f|
							- i +=1
							%tr
								%td
									= i
								%td{ :class=> "col-md-11" }
									= Phase.find_by(id: 3).activities.second.questions.find_by(seq: i).content
								%td.text-center
									= f.radio_button :not_doing_adaptation, 'false'
								%td.text-center 
									= f.radio_button :not_doing_adaptation, 'true'
								%td.text-center 
									= f.radio_button :not_doing_adaptation, 'dk'
							- if i == 14
								%tr
									%td{ :colspan => 5}
										%h5
											Do you anticipate making the following context adaptations to the intervention you are considering at your agency:
					= submit_tag 'Save', class: 'btn btn-primary', :style => "display:none;"
					
			%btn.btn.btn-primary.pull-right#adaptationsList
				Save

app/views/activities/phase_3_step_1_activity_3.html.haml
.container
	.row
		.col-sm-12
			%ol.breadcrumb
				%li
					= link_to 'Dashboard', dashboard_index_path
				%li
					= link_to 'Phase 3', phase_path( 3 )
				%li
					= link_to 'Step 1', phase_step_path( @phase, @step )
				%li
					Activity 3: Treatment Adaptations Table
	.row
		.col-sm-12
			%h1
				Activity 3: Treatment Adaptation Plan
			%p
				To review instructions, see
				= link_to 'Phase 3 Step 1 guide', phase_step_path( @phase, @step )

			- if @current_agency.treatment_adaptations.where( not_doing_adaptation: 'false').count == 0 && @current_agency.treatment_adaptations.where( not_doing_adaptation: 'dk').count == 0
				Please complete 
				= link_to 'Activity 3.1.2', '/phases/3/steps/6/activities/12'
				to populate required forms below.
			- else
				= form_tag update_individual_treatment_adaptations_path, :method => "put", :id => "myAdaptationsForm" do |f|	
					- for treatment_adaptations in @current_agency.treatment_adaptations.order('created_at ASC')
						=fields_for "treatment_adaptations[]", treatment_adaptations do |f|
							- if treatment_adaptations.not_doing_adaptation != 'true'
								%h4{ style: 'margin-bottom: -6px;' }
									= treatment_adaptations.name
								%br
								%table.table.table-bordered	
									%thead
										%th
											%center Specify reason(s) for the adaptation
										%th{"data-toggle" => "tooltip", "data-container" => "body", "title" => "To help identify potential concerns, consult with others who are knowledgeable about the agency and/or the research-based treatment (e.g., adaptation team, implementation team, stakeholders/consumers, agency staff, treatment developers, etc.). Pay particular attention to any concerns that adaptations will impact the effectiveness of the intervention."}
											%center Identify any specific concerns about the adaptation
										%th
											%center How will concerns be addressed?
										%th{"data-toggle" => "tooltip", "data-container" => "body", "title" => "Detail the specific steps of each adaptation that will be made. This may include the content or context of the treatment that will be adapted (e.g., the treatment modules will be reordered so that module three will precede module two.)."}
											%center Specify how the adaptation will be made
										%th
											%center Who will carry out the adaptation?
									%tbody
										%tr
											%td
												= f.check_box :org_level
												Organization-level factors (e.g., training space and resources, session time, treatment duration, agency philosophy/fit)
												%br
												= f.check_box :provider_factors
												Provider factors (e.g., education level, discipline, experience, receptivity to innovation, attitudes towards innovation)
												%br
												= f.check_box :client_chars
												Client characteristics (e.g., age, developmental age, ASD diagnosis, severity, culture, language, comorbid problems)
												%br
												= f.check_box :system_level
												System-level factors (e.g., funding/resources, internal or contracted services, politics, policies)
												%br
												=# f.text_area :other_reasons
											%td
												= f.radio_button :concerns, true
												No concerns
												%br
												= f.radio_button :concerns, false
												Concerns exist
												%br
												%br
												List concerns:
												= f.text_area :other_concerns
											%td
												= f.check_box :proceed_with_plan
												Proceed with adaptation plan
												%br
												= f.check_box :seek_further_consultation
												Seek further consultation
												%br
												= f.check_box :address_concern
												Address concern
												%br
												%br
												If "Address concern" was chosen, please list how:
												%br
												= f.text_area :address_concern_text
											%td
												= f.text_area :adaptation_details, :rows => 10
											%td
												= f.check_box :treatment_developer
												Treatment Developer
												%br		
												= f.check_box :researcher
												Researcher
												%br		
												= f.check_box :agency_leader
												Agency Leader
												%br		
												= f.check_box :supervisor
												Supervisor
												%br	
												= f.check_box :direct_provider
												Direct Provider
												%br	
												= f.check_box :implementation_team
												Implementation Team
												%br	
												Other:
												%br
												= f.text_area :other_implementer
										%tr
											%td{ :colspan => '5' }
												= f.radio_button :not_doing_adaptation, 'true'
												No longer planning to conduct this adaptation
												%br
												= f.radio_button :not_doing_adaptation, 'false'
												Still going forward with adaptation
												%br
												= f.radio_button :not_doing_adaptation, 'dk'
												Uncertain
												.pull-right= submit_tag 'Save', class: 'btn btn-primary'

					= submit_tag 'Save', class: 'btn btn-primary'